name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run tests
        run: cargo test --verbose
 
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
    
      - name: cargo fmt
        run: cargo fmt -- --check
      
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
